SHOW_SQL: true
JWT_SECRET: absfol7814lqmva7891294nn9asa783nr293urnq9adm38ry2

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect