server:
  error:
    include-message: always
  port: 8080
management:
  server:
    port: 9080

spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${DATASOURCE_URL}/${DATASOURCE_DATABASE}
    username: ${DATASOURCE_USER}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: -1

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  show-login-endpoint: true
  show-actuator: true

jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    root: info
  file:
    name: archiver-app.log

aws-s3-config:
  bucket-name: archived
  backup-bucket-name: archived-backup
  access-Key: ${AWS_ACCESS_KEY:minio}
  secret-Key: ${AWS_ACCESS_KEY:minio123}
  s3endpoint: ${AWS_S3_URL:http://127.0.0.1:9000}